# Generated by Django 6.0.1 on 2026-01-27 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_advertisements', to=settings.AUTH_USER_MODEL),
        ),
    ]
